title: "tachesimazzoca - Wiki"

url: "http://tachesimazzoca.github.io"
baseurl: "/wiki"

source: .
destination: ./_site
plugins: ./_plugins

markdown: rdiscount 

rdiscount:
  extensions:
    - strict

highlighter: pygments
