pipeline:
  build:
    image: hseeberger/scala-sbt:8u181_2.12.6_1.2.1
    commands:
      - sbt paradox

  publish:
    image: hseeberger/scala-sbt:8u181_2.12.6_1.2.1
    commands:
      - bin/drone-publish.sh
    secrets: [ github_ssh_key ]
    when:
      branch: master
