pipeline:
  build:
    image: hseeberger/scala-sbt:8u181_2.12.6_1.2.1
    commands:
      - sbt paradox

  publish:
    image: tachesimazzoca/pipeline-base
    commands:
      - echo "$${GITHUB_SSH_KEY}" | pipeline-ssh-key id_rsa
      - pipeline-ssh-config-add github-tachesimazzoca git github.com
      - echo y | bin/publish.sh
    secrets: [ github_ssh_key ]
    when:
      branch: master
