<div id="footer">
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <dl class="dl-horizontal pull-right">
        <dt><span class="muted">Repository</span></dt>
        <dd><a href="https://github.com/tachesimazzoca/wiki">tachesimazzoca/wiki</a></dd>
        <dt><span class="muted">Author</span></dt>
        <dd><a href="https://github.com/tachesimazzoca">@tachesimazzoca</a></dd>
      </dl>
    </div>
  </div>
</div>
</div>
<!--/#footer-->
