<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="refresh" content="5;URL=$page.properties.("redirect.location")$">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>tachesimazzoca - Wiki | $page.title$</title>
<link href="$page.base$assets/lib/bootstrap-3.2.0/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="$page.base$assets/stylesheets/style.css" media="screen" rel="stylesheet" type="text/css">
<script src="$page.base$assets/lib/jquery-1.11.1/jquery.min.js"></script>
<script src="$page.base$assets/lib/bootstrap-3.2.0/js/bootstrap.min.js"></script>
$gtm()$
</head>
<body>
<div id="wrapper">
  $header()$
  <div id="main">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <p>This page has moved to <a href="$page.properties.("redirect.location")$">$page.properties.("redirect.location")$</a>. Redirecting ...</p>
        </div>
      </div>
    </div>
  </div>
  <!--/#main-->
  $footer()$
</div>
<!--/#wrapper-->
</body>
</html>
