<form class="navbar-form navbar-right" action="https://www.google.com/search" style="box-shadow: none; border: none">
  <input type="hidden" name="as_sitesearch" value="tachesimazzoca.github.io/wiki">
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon" style="background: transparent; border-color: #333">
        <span class="glyphicon glyphicon-search"></span>
      </div>
      <input type="text" class="form-control" name="as_q" placeholder="Search">
    </div>
  </div>
</form>
